# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2773997ddf70af4b3a81d7474b9279b89b8def67df2b33cada875f9efc422efe2eb1fad31f360a7aa11ead7bdf5cc17968dc71437acc2f6d7ee337ea2e59e5a6

test:
  secret_key_base: 353bacdf11a6183136cbdde51d7b889855600041cdadcaf4d85bf3bb66e31f2e169017a9f73e0adbd9a5ed1fa8a62a77c25354814dea9afe5e2ac0b710e6a202

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
